# Generated by Django 3.1.6 on 2021-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20210207_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_tag',
        ),
        migrations.AlterField(
            model_name='book',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
