# Generated by Django 3.1.6 on 2021-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20210207_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=250, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
